### PR TITLE
rough in an angularized organizers dashboard

### PR DESCRIPTION
**Pull request by chadwhitacre**
#364 needs this for context.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Need to constrain the organizers listed for the user under `/organizers.json` to only those they have permissions on ...

**Comment by dmtroyer** [comment]
> Need to constrain the organizers listed for the user under /organizers.json to only those they have permissions on ...

Are you talking rails API side @whit537? 

If so, I have a use case where I am going to need the whole list of organizers as a public API. Could you put this at `users/:id/organizers` or sumpin?

**Comment by chadwhitacre** [comment]
> Are you talking rails API side @whit537?

Yes! :-)

> If so, I have a use case where I am going to need the whole list of organizers as a public API. Could you put this at `users/:id/organizers` or sumpin?

Sure thing! :-)

**Comment by chadwhitacre** [comment]
Roughed in in f2081b654c99e4b86382a3313f3151a84591b6f9, @dmtroyer. Now to constrain it ...

**Comment by chadwhitacre** [comment]
screen shot 2015-12-14 at 4 50 11 pm

**Comment by chadwhitacre** [comment]
Blam.

screen shot 2015-12-14 at 4 51 42 pm

**Comment by chadwhitacre** [comment]
A second user + organizer, demonstrating working constraint:

screen shot 2015-12-14 at 4 52 46 pm

**Comment by chadwhitacre** [comment]
screen shot 2015-12-14 at 4 55 51 pm

**Comment by chadwhitacre** [comment]
Do you think this PR needs to reproduce all of the functionality currently available in the rails dashboard?

**Comment by chadwhitacre** [comment]
On second thought, let's keep the scope tight on this PR. Marking ready for review, @dmtroyer @MatthewVita.

**Comment by MatthewVita** [comment]
Looks good to me

**Comment by dmtroyer** [comment]
The list of organizers at `dashboard/organizers` wasn't working for me when I was logged out of the rails-side dashboard. The `organizers/for-current-user` endpoint needed to be moved within the `api/v1` scope to `api/v1/organizers/for-current-user` for `ng-token-auth` to attach the necessary headers so that the user could be authenticated that way (and `current_user` would work), instead of with the rails-side devise cookie like it was previously doing.

Eventually we should move all the routes within this scope.

@whit537 let me know if that makes sense and/or if you have any questions. To bed! :zzz:

**Comment by chadwhitacre** [comment]
Rebased on master. Previous head was c634a910c99abf059674a7b1533f970453442be5.

**Comment by chadwhitacre** [comment]
I'm gonna go ahead and squash this according to https://github.com/saxifrage/cityasacampus/issues/362#issuecomment-162029375 et seq.

**Comment by chadwhitacre** [comment]
Squashed. Previous head was 44098cf4c6499bb00450d2c0c1d72fb2c26e764f.

**Comment by chadwhitacre** [comment]
Resquashed. Previous head was 95e010b99a135d3035347fe3e17d42613ece8148.

**Comment by chadwhitacre** [comment]
I'm getting a 401 from `organizers/for-current-user.json` for anon. That's good.

screen shot 2015-12-21 at 10 23 45 am

**Comment by chadwhitacre** [comment]
Gonna stub out the buttons on the organizers dashboard:

screen shot 2015-12-21 at 10 28 00 am

**Comment by chadwhitacre** [comment]
Resquashed. Previous was 544033790e9b38138d5335a8cf9067d9be5c596c.

**Comment by chadwhitacre** [comment]
Alright, we ready to merge, @dmtroyer?

**Comment by chadwhitacre** [comment]
Ping @dmtroyer @MatthewVita ... ready for a review and merge over here ...

**Comment by chadwhitacre** [comment]
Thanks @dmtroyer. :)

**Pull request merged**
