### PR TITLE
standardize dev env

### PR DESCRIPTION
**Pull request by chadwhitacre**
Follow-on from #358.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Basically I think we should use Heroku buildpacks to build locally, to keep dev and production as similar as possible.

**Comment by chadwhitacre** [comment]
Gosh, we should really have tests. :-(

**Comment by chadwhitacre** [comment]
https://docs.travis-ci.com/user/customizing-the-build/

**Comment by chadwhitacre** [comment]
I'm abandoning this until after we have CI.

**Comment by MatthewVita** [comment]
@whit537:

> Gosh, we should really have tests. :-(

I agree, but we opted to wait until stage 3 of the roadmap (http://cityasacampus.org/doc/roadmap.html), which is post-MVP to write the unit tests. Not very conventional, but unit tests, logging, and great documentation are all called out under the "tech debt" label that I'll make an epic for post-MVP.

**Pull request closed without merging**
