### PR TITLE
User registration

### PR DESCRIPTION
**Pull request by dmtroyer**
Let the user registration begin!

### CODE REVIEW

**Comment by MatthewVita** [comment]
issue in milestone is here: https://github.com/saxifrage/cityasacampus/issues/368

**Comment by dmtroyer** [comment]
I'm running into an issue with permitting additional user fields at user registration. It seems similar to https://github.com/lynndylanhurley/devise_token_auth/issues/432

**Comment by dmtroyer** [comment]
When I add one field at a time to the `devise_parameter_sanitizer` it seems to work

``` ruby
devise_parameter_sanitizer.for(:sign_up) << :name
```

but when I try to pass it a block it doesn't permit the additional fields

``` ruby
devise_parameter_sanitizer.for(:sign_up) { |u| u.require(:name, :email, :password, :password_confirmation) }
```

I'm guessing it has something to do with the `devise_token_auth` controller. Will dig :hammer:

**Comment by dmtroyer** [comment]
Ok I think I realize what is going on.

The way `devise_token_auth` calls `devise_parameter_sanitizer.for(:sign_up)` will never hit the block that is used to register permitted parameters

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/registrations_controller.rb#L99-L101

``` ruby
def sign_up_params
  params.permit(devise_parameter_sanitizer.for(:sign_up))
end
```

**Comment by dmtroyer** [comment]
`devise_token_auth` should be using the `devise_parameter_sanitizer.sanitize(:sign_up)` method in `RegistrationsController.sign_up_params` instead of the `for` method

**Comment by dmtroyer** [comment]
but `Devise::ParameterSanitizer.resource_name` is `:api_user` instead of `:registrations`

**Comment by dmtroyer** [comment]
The issue on `devise_token_auth` where I go into more detail https://github.com/lynndylanhurley/devise_token_auth/issues/464

**Comment by chadwhitacre** [comment]
!m @dmtroyer

**Comment by dmtroyer** [comment]
Gee beez it this is up for review. I could have probably done more to directiveify the Organizer Registration view but I needed to draw the line somewhere and move on.

**Comment by MatthewVita** [comment]
@dmtroyer the code looks excellent!

Comments:
- I just amended your commit correcting a few areas not using string-based injection (please read "A Note on Minification" https://docs.angularjs.org/tutorial/step_05
- Your paths to the SVGs were incorrect so I fixed them :+1:

**Comment by dmtroyer** [comment]
> I just amended your commit correcting a few areas not using string-based injection (please read "A Note on Minification" https://docs.angularjs.org/tutorial/step_05

Ah hah! Thanks for the link, I wondered why we were doing that :wink:

> Your paths to the SVGs were incorrect so I fixed them :+1:

Shanks!

**Pull request merged**
