### PR TITLE
implement token auth

### PR DESCRIPTION
**Pull request by chadwhitacre**
This is for #347, ya @dmtroyer @MatthewVita?

### CODE REVIEW

**Comment by chadwhitacre** [comment]
The three provisioning commits (3420524, 09bb778, 3a289d9) seem out of place on this PR, and are the source of the conflicts with `master` (cf. #355 #356). I'm going to rebase them off of this branch.

**Comment by chadwhitacre** [comment]
Done. Previous head was 37a5a2ce48664fccf03ebdffe8999fca714220da.

**Comment by dmtroyer** [comment]
Was there a `--force` update on `master`?

**Comment by chadwhitacre** [comment]
> Was there a `--force` update on `master`?

@dmtroyer Not that I'm aware of. I force-pushed the `token-auth` branch to get this PR out of conflict with master.

**Comment by dmtroyer** [comment]
Ok, weird. I checked out `master` and pulled and had a bunch of conflicts. All good now.

**Comment by chadwhitacre** [comment]
> Ok, weird. I checked out `master` and pulled and had a bunch of conflicts. All good now.

Okay, cool.

How can I help here? Or is there something better for me to work on?

**Comment by dmtroyer** [comment]
> How can I help here? Or is there something better for me to work on?

I think right now it is unfortunately at a place that is hard to break out into smaller discrete items. Maybe once we get the login merged it would make sense to start breaking it out into smaller pieces.

**Comment by chadwhitacre** [comment]
@dmtroyer Okay, I'm going to familiarize myself with what we have now and with Angular in general.

**Comment by dmtroyer** [comment]
OK! This bad boy's ready for review. Token auth is wired up for both sides, the only thing implemented on the Angular UI Side is the login page at `#/users/login`. If you want to do anything with that authentication, it will take a bit of a read up on [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth) if you beat me to establishing that pattern.

**Comment by MatthewVita** [comment]
Looking good, @dmtroyer! I just threw this together real quick to make use of a directive and a generic auth service: https://github.com/saxifrage/cityasacampus/commit/49b83fd910e3937910c03de5bf1ad42c8fd90412

Are you okay with these tweaks?

Also, since Chad and I just merged our Heroku branch, this branch is going to need some love to catch up with master... whoops :+1:

**Comment by MatthewVita** [comment]
ahh... should have named 'AuthService' not 'LoginService'. Will amend that soon going to bed now

**Comment by dmtroyer** [comment]
@MatthewVita I can make the change and rebase.

**Comment by chadwhitacre** [comment]
> the only thing implemented on the Angular UI Side is the login page at `#/users/login`.

How can I test this out, @dmtroyer? When I navigate to `/#/users/login` I get a blank page.

screen shot 2015-12-04 at 2 19 22 pm

**Comment by dmtroyer** [comment]
@whit537 did you run gulp on this branch?

**Comment by dmtroyer** [comment]
You'll also have to run `npm i` and `bundle install` to install some dependencies

**Comment by chadwhitacre** [comment]
Yup. Ran all three.

**Comment by chadwhitacre** [comment]
Aaaaand I have a login form now. :-)

screen shot 2015-12-04 at 2 43 58 pm

**Comment by chadwhitacre** [comment]
I'm seeing `[...] auth_headers=%7B%22access-token%22[...]` in the request cookie.

**Comment by MatthewVita** [comment]
> I'm seeing [...] auth_headers=%7B%22access-token%22[...] in the request cookie.

Yep. Would prefer if this library used Session Storage, but oh well.

@dmtroyer: can I merge this ? UPDATE: I forgot to add that we may want to merge this now, as is, and create separate PRs/Issues for forgot password, logout, password reset, etc. This PR is the base for all of that.

**Comment by MatthewVita** [comment]
also, was able to verify that post-login, the library intercepts all Angular `$http` requests to provide the token. :+1:

**Comment by dmtroyer** [comment]
> Yep. Would prefer if this library used Session Storage, but oh well.

I believe it can be configured to use local storage instead of cookies. Something has to be stored client-side.

> I forgot to add that we may want to merge this now, as is, and create separate PRs/Issues for forgot password, logout, password reset, etc. This PR is the base for all of that.

Exactly. I started to work on password reset and registration and realized that extended beyond the scope of this PR. I'll start some new prs for those with the work I started once I get a chance this weekend.

> can I merge this ?

Ready to go as far as I'm concerned.

**Comment by MatthewVita** [comment]
> I believe it can be configured to use local storage instead of cookies.

Local storage is better but the best practice is session storage. If it's trivial to do, I'll put in a PR for the library.

> Ready to go as far as I'm concerned.

Woo

**Comment by chadwhitacre** [comment]
!m @dmtroyer @MatthewVita

**Comment by MatthewVita** [comment]
> Local storage is better but the best practice is session storage. If it's trivial to do, I'll put in a PR for the library.

I'm going to do this work here: https://github.com/saxifrage/cityasacampus/issues/370

**Pull request merged**
