### PR TITLE
full text search

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Comment by justinxreese** [comment]
The only thing I'm worried about is the migration failing if heroku doesn't let us do that postgres add-on via SQL. All else looks good. Do you think we should try it on the command line or just go with this?

**Comment by MatthewVita** [comment]
only one way to find out...

but seriously, my understanding is that as long as the Postgres install on Heroku is up to date and the executing user has the correct privileges, the migration should run without issue.

do you want me to explore other concerns before we merge? Let me know if I'm overlooking something.

**Comment by justinxreese** [comment]
Nah, no problem moving forward. You'll need to rebase your branch. there's also something causing the deploy to fail that I haven't had a chance to look into. something along the lines of a duplicate key

**Comment by MatthewVita** [comment]
@justinxreese I rebased my branch but the CI is failing with that index error :(. Any ideas around how to fix that?

**Pull request merged**
