### PR TITLE
adds google maps to opportunity instances page

### PR DESCRIPTION
**Pull request by MatthewVita**
@whit537, since you're the maps wizard, mind doing a quick code review for our Google Maps embed on the opportunity pages?

The main areas you'll be interested in are:
- https://github.com/saxifrage/cityasacampus/blob/795322a9c8c29733bd3436c8c295e4d2aa074559/client/app/shared/geo/GoogleMapsDirective.js
- https://github.com/saxifrage/cityasacampus/blob/795322a9c8c29733bd3436c8c295e4d2aa074559/client/app/shared/geo/GeocoderService.js
- https://github.com/saxifrage/cityasacampus/blob/795322a9c8c29733bd3436c8c295e4d2aa074559/client/app/opportunity-instances/OpportunityInstancesView.html

capture

### CODE REVIEW

**Comment by timothyfcook** [comment]
@whit537 can you review this PR on Friday?

**Comment by chadwhitacre** [comment]
Yes!

**Comment by chadwhitacre** [comment]
lgtm :)

**Comment by MatthewVita** [comment]
@whit537 Thank you for the code review.

img

**Pull request merged**
