### PR TITLE
Build sign up form for organization admins

### PR DESCRIPTION
**Pull request by sdanko11**
- Created `organizer_users` table
- Added `name` to `users`
- Built form for `users` to register and create their `organization`

### CODE REVIEW

**Comment by dmtroyer** [comment]
Awesome work, @sdanko11!

Hate to be _that guy_, but I think this needs a little bit of tweaking to integrate with devise views to ensure we can login after registration.

I think this might be as simple as reverting `config/routes.rb:5` back to the [`devise_for` routing mapper](http://www.rubydoc.info/github/plataformatec/devise/master/ActionDispatch/Routing/Mapper#devise_for-instance_method) and taking the work you've done in `app/views/users/new.html.erb` and putting it in the devise view at `app/views/devise/registrations/new.html.erb`

thoughts? @MatthewVita?

screenshot - 10092015 - 01 22 35 pm

**Comment by dmtroyer** [comment]
Ok, thinking about this some more @sdanko11 @MatthewVita @timothyfcook  sorry to make it complicated but I went to get started on some other admin dashboard stuff and I think most of that hinges on this.

I like how this fulfills the data model requirements of #240, where I need a little bit more clarity is how the form addresses #196.

Some questions that follow from that regarding this implementation:
- How will a "learner" `user` register? This is just a `user` without an `organizer_user`, correct?
- How will a `user` become associated with more than one `organizer`? (Whether or not that `organizer` already exists.

Maybe we just add more issues/user stories to address some of what falls out from this discussion and move on from there?

Otherwise I like this pull request other than the fact that it breaks logging in.

Thanks for your patience, trying to come up to speed on this project as well as quickly as possible!

**Comment by timothyfcook** [comment]
- There are no "learner" `user` accounts for the MVP. Correct, `user` with a `null` value in `associated_organizer` should be a "learner"
- @sdanko11 talked about making a new table for this

**Comment by MatthewVita** [comment]
@sdanko11: Nice clean code.

Comments:
- You may want to rebase your branch with master because I merged @dmtroyer's changes which may conflict a bit with your work.
- Like @dmtroyer said, you'll need to leverage devise in terms of the routes and use its views
- After a user is successfully created, redirect them to the dashboard index page (https://github.com/saxifrage/cityasacampus/blob/master/app/views/dashboard/index.html.erb)
- Instead of using `new.html.erb`, use something like `organizer-registration.html.erb`, so we can call out `learner-registration.html.erb` later on.

Appreciate the feedback from @timothyfcook and @dmtroyer here. Please let me know what I can do to help you.

**Comment by sdanko11** [comment]
@MatthewVita I was thinking right along with your strategy.  I was not sure when we would be implementing the learner registration so I decided to keep it as one controller action for now.  I agree though we should specify the action even if learner registration is not implemented yet.  I will fix this.

**Comment by sdanko11** [comment]
@dmtroyer @MatthewVita 

What I ended up doing is disabling the devise registrations routes and then creating a `RegistrationsController` which manually signs the `User` in after a successful account creation.  

It becomes a real pain to use `accepts_nested_attributes` with devise on registration, so thats why I took this route.  We're not losing any of the power of devise.

**Comment by MatthewVita** [comment]
@sdanko11 I like how you coupled devise to users. I'm seeing this error though... any help?

asdf

**Comment by sdanko11** [comment]
@MatthewVita that link is routing to the old devise sign in route.  Now that we have split the signup for `leaners`and `organizers`, the route is not valid.  I have not yet set up the sign up for learners.  I would just replace that link with a link to `root_path` until we set up the login for learners.  Let me know if you have any more questions.

**Comment by MatthewVita** [comment]
@sdanko11 thanks for the information. I've merged the PR.

We have 2 actionables:
- [x] @matthewvita to add "dashboard/registrations/organizer_registration" link to the frontend
- [x] @sdanko11 to investigate the following error when pressing "Create Account": 

```
Template is missing
Missing template registrations/new, application/new with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in: * "/usr/local/lib/ruby/gems/2.1.0/gems/web-console-2.0.0/lib/action_dispatch/templates" * "/home/matthew/code/cityasacampus/app/views" * "/usr/local/lib/ruby/gems/2.1.0/gems/devise-3.5.1/app/views" * "/usr/local/lib/ruby/gems/2.1.0/gems/kaminari-0.16.3/app/views"
```

**Pull request merged**
