### PR TITLE
fix vertical whitespace on a couple pages

### LINKED ISSUE #334: Tighten Up Vertical Whitespace On Opportunity Instances
I propose that on opportunity instance pages, the blue facts/register area should be flush up against the map-ish header background, with no intervening gray strip:

screen shot 2015-11-06 at 9 30 32 am

### PR DESCRIPTION
**Pull request by chadwhitacre**
Fixes #334.
- [x] opportunity instance
- [x] homepage

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Actually, I think the better fix for this would be to unclip the SVG background.

**Comment by chadwhitacre** [comment]
Which is to say that the SVG background is only about 620 pixels high.

**Comment by chadwhitacre** [comment]
Worked around the hero SVG limitation with some judicious application of `margin-bottom`.

# Before

screen shot 2015-11-06 at 12 50 27 pm
screen shot 2015-11-06 at 12 50 37 pm

# After

screen shot 2015-11-06 at 12 50 56 pm
screen shot 2015-11-06 at 12 50 51 pm

**Comment by chadwhitacre** [comment]
Ready for review, @cameronscott137 @chelseaerdner @MatthewVita et al. :-)

**Comment by MatthewVita** [comment]
wonderful.

**Pull request merged**
