### PR TITLE
Adds small amount of seed data

### LINKED ISSUE #75: Add Seed Data to DB

### PR DESCRIPTION
**Pull request by justinxreese**
Fixes #75

To seed your local copy run `rake db:seed`

### CODE REVIEW

**Comment by justinxreese** [comment]
@whit537 review

**Comment by timothyfcook** [comment]
is this seed data not served up on learnpgh.herokuapp.com ?

**Comment by justinxreese** [comment]
It is not. I don't know that seed data should be on a pseudo-production environment? It'd be as simple as running a script. But it's more of a theoretical debate

To test against seed data, we should do it by running a server locally

**Comment by timothyfcook** [comment]
Cool, just seems like we'll want some data to populate the Explore page when the design is live. Would it be helpful if I added more?

**Comment by justinxreese** [comment]
We have three options right now
- we could maintain this copy of app as a demo application and be okay with a bunch of junk data
- we could keep the data clean so that any real organizations that we pilot this with can use this copy of app
- do both of those things, but with separate instances of the app. This would require maintaining another copy of the app

**Comment by MatthewVita** [comment]
I vote for option 3... this way, we'll have a production LearnPGH environment and a development CaaC environment to mess with.

**Comment by MatthewVita** [comment]
...however, this can come later on as our app is still so early on we can just stand up things locally

**Comment by justinxreese** [comment]
Yeah. I lean 3 too. Just need to carve out time for it. Shouldn't take long, but would involve tweaking the development and deployment process a little.

**Pull request merged**
