### PR TITLE
UI for creating pathways

### LINKED ISSUE #201: Dashboard Create Pathway
Once #198 is complete, we need to add another option that will allow users to create their own custom maps

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes #201.
## To-do

Based on https://github.com/saxifrage/cityasacampus/pull/364#issuecomment-162681923.
### WIP on #377
- [x] add ~~topics~~ _grids_ under "All ~~Topics~~ _Grids_"
- [x] load a ~~topic~~ _grid_ by clicking on it under "All ~~Topics~~ _Grids_"
- [x] add pathways under ~~"$Topic"~~ _"$Grid"_
- [x] load a pathway by clicking on it under "$Pathway"
### WIP on #384
- [x] remove ~~topics~~ _grids_ under "All ~~Topics~~ _Grids_" (drag to garbage can? little clicky `x` or trashcan when loaded?)
- [x] rename a ~~topic~~ _grid_
- [x] remove pathways under ~~"$Topic"~~ _"$Grid"_
- [x] rename a pathway
- [x] keep "All ~~Topics~~ _Grids_" and ~~"$Topic"~~ _"$Grid"_ alphabetized
### WIP on #385
- [ ] constrain "Library" list by organizer and not-already-on-a-pathway-for-the-given-workflow-state
- [ ] add/remove resources from $Pathway
### Bumped (https://github.com/saxifrage/cityasacampus/pull/364#issuecomment-166408512)
- add a [ Preview ] button that hits caac-map.net and stores the SVG
- add a [ Publish ] button that copies the preview map to the published map (overwriting any previous published map)
- show the published map at `/:organizer/map`
- show the preview map at `/:organizer/map/preview` (admin-only)

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Alright, so where is our client-side routing implemented?

**Comment by chadwhitacre** [comment]
[`client/index.js`](https://github.com/saxifrage/cityasacampus/blob/72eaf1e744ced14e2a5141513fc3fe05e40d1ad9/client/index.js#L23-L39), looks like ...

**Comment by chadwhitacre** [comment]
I made a `client/dashboard/PathwaysView.html` file, and wired it up in `index.js`, but it's not available through the web. Our Gulp asset pipeline is not copying it over into `public/dashboard/` as I would expect. How do I tell Gulp to do that?

**Comment by chadwhitacre** [comment]
Looks like [`templates`](https://github.com/saxifrage/cityasacampus/blob/72eaf1e744ced14e2a5141513fc3fe05e40d1ad9/gulpfile.js#L70-L73) is the task responsible for copying the file over.

**Comment by chadwhitacre** [comment]
Why isn't it?

**Comment by chadwhitacre** [comment]
Hrm, it's there now. :-/

**Comment by chadwhitacre** [comment]
:shrug:

screen shot 2015-12-04 at 5 25 31 pm

**Comment by chadwhitacre** [comment]
Alright, there's a start, anyway. I plan to pick up with this on Monday, hopefully at the Sprout office! :-)

**Comment by MatthewVita** [comment]
Lookin' good, @whit537. Adding a couple commits for housekeeping.

**Comment by chadwhitacre** [comment]
Cool, thanks @MatthewVita. :-)

**Comment by chadwhitacre** [comment]
Rebased on master now that #357 has landed. Previous head was d4458add7a311982b4200903705de039782aa460.

**Comment by chadwhitacre** [comment]
https://github.com/marceljuenemann/angular-drag-and-drop-lists

**Comment by chadwhitacre** [comment]
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple

Looks about right:

screen shot 2015-12-07 at 9 56 21 am

**Comment by chadwhitacre** [comment]
I am working on installing `angular-drag-and-drop-lists` into our application.

**Comment by chadwhitacre** [comment]
My first step is to get [the code](https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/angular-drag-and-drop-lists.min.js) into our `public/vendors.min.js`.

**Comment by chadwhitacre** [comment]
I've added the following to our `package.json`:

```
    "angular-drag-and-drop-lists": "marceljuenemann/angular-drag-and-drop-lists#822552b2b6fe28fa7675ec434c769fa96ba5e154",
```

**Comment by chadwhitacre** [comment]
I've run `npm install` and `npm ls` shows `angular-drag-and-drop-lists` to be installed:

```
$ npm ls|grep angular
├── angular@1.3.14
├── angular-cookie@1.0.0 (git+https://github.com/ivpusic/angular-cookie.git#67eb8455445dfbf38d23f17e3a0b9af773b03d77)
├── angular-drag-and-drop-lists@1.3.0 (git+https://github.com/marceljuenemann/angular-drag-and-drop-lists.git#822552b2b6fe28fa7675ec434c769fa96ba5e154)
├── angular-filter@0.5.4
├── angular-route@1.3.14
$
```

**Comment by chadwhitacre** [comment]
From [`angular-drag-and-drop-lists`' `package.json`](https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/package.json), I expect the `angular-drag-and-drop-lists.js` file to end up in our `node_modules`, and for gulp to include it from there when creating `vendors.min.js`.

**Comment by chadwhitacre** [comment]
Looks like I have to add it to the gulpfile ...

**Comment by chadwhitacre** [comment]
Yay! :-)

screen shot 2015-12-07 at 10 23 59 am

I had to rerun gulp. The gulp watcher wasn't apparently smart enough?

**Comment by chadwhitacre** [comment]
Now I'm working on getting the [simple demo](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple) installed into the stub pathways page.

**Comment by chadwhitacre** [comment]
29a6a676df4709c0b61cdd1ecfd4ea75084e82b3 is giving me the `pre` with the computed dummy data, but I'm not getting the `ul` items.

screen shot 2015-12-07 at 10 31 23 am

**Comment by chadwhitacre** [comment]
So Angular has some kinda scopes, right? And the DOM has to match or be scoped or whatever with the controller?

**Comment by chadwhitacre** [comment]
`modelAsJson` appears to be in scope in the DOM.

**Comment by chadwhitacre** [comment]
Where does `list` come from in https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/demo/simple/simple.html#L8?

**Comment by chadwhitacre** [comment]
Looks like it comes from https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/demo/simple/simple-frame.html#L13.

**Comment by chadwhitacre** [comment]
Boom!

screen shot 2015-12-07 at 10 51 09 am

**Comment by chadwhitacre** [comment]
Okay! Ready to start getting the drag/drop itself actually working. :-)

screen shot 2015-12-07 at 10 59 02 am

**Comment by chadwhitacre** [comment]
Alright! Where the heck is the drag-n-drop?

**Comment by chadwhitacre** [comment]
What is click supposed to do and why isn't it doing it in my case?

**Comment by chadwhitacre** [comment]
https://github.com/marceljuenemann/angular-drag-and-drop-lists/pull/186 :hamburger:

**Comment by chadwhitacre** [comment]
The demo has a click event listed in the DOM inspector:

screen shot 2015-12-07 at 11 35 18 am

Ours doesn't:

screen shot 2015-12-07 at 11 35 56 am

**Comment by chadwhitacre** [comment]
Alright, how the heck do I debug this?

**Comment by chadwhitacre** [comment]
Let's read [the docs](https://github.com/marceljuenemann/angular-drag-and-drop-lists#readme) ...

**Comment by chadwhitacre** [comment]
BTW, what's our browser support target, @MatthewVita @dmtroyer @timothyfcook? I'm not seeing an answer on http://cityasacampus.org/ ...

**Comment by chadwhitacre** [comment]
> `dnd-draggable` Required attribute. The value has to be an object that represents the data of the element. In case of a drag and drop operation the object will be serialized and unserialized on the receiving end.

https://github.com/marceljuenemann/angular-drag-and-drop-lists#dnd-draggable-directive

**Comment by chadwhitacre** [comment]
> The value has to be an object that represents the data of the element.

Why is this `item` in the demo? Do I have some plumbing wrong?

**Comment by chadwhitacre** [comment]
> Why is this `item` in the demo?

Probably from the `item in list` `ng-repeat`?

**Comment by chadwhitacre** [comment]
... which I believe is working because `{{item.label}}` appears to be working.

**Comment by chadwhitacre** [comment]
More to the point: the demo has `drag{start,end}` events, and we don't:

screen shot 2015-12-07 at 12 03 31 pm

**Comment by chadwhitacre** [comment]
The `(program):34` links are unhelpful. They go to:

```
chrome-devtools://devtools/bundled/inspector.html?&remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@deadbeef/&can_dock=true&dockSide=undocked
```

**Comment by chadwhitacre** [comment]
And that's an empty page:

``` html
<!--
 * Copyright 2014 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
-->
<!doctype html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Security-Policy" content="object-src 'none'; script-src 'self' 'unsafe-eval' https://chrome-devtools-frontend.appspot.com">
    <link rel="stylesheet" type="text/css" href="inspector.css">
    <script type="text/javascript" src="inspector.js"></script>
</head>
<body class="undocked" id="-blink-dev-tools"></body>
</html>
```

**Comment by chadwhitacre** [comment]
Is Angular not running properly on this page?

**Comment by chadwhitacre** [comment]
I don't see any Angular-y events on the `html` element (I'm now using the Firefox web inspector since Chrome's events helper was unhelpful):

screen shot 2015-12-07 at 12 09 43 pm

**Comment by chadwhitacre** [comment]
I do see some on the demo:

screen shot 2015-12-07 at 12 11 09 pm

**Comment by chadwhitacre** [comment]
Well, I guess we bundle Angular into `vendors.min.js`.

**Comment by chadwhitacre** [comment]
My hunch is that @MatthewVita and/or @dmtroyer could point me in the right direction pretty quickly here.

**Comment by chadwhitacre** [comment]
Barring that, I suppose it's time to go spelunking in Angular ...

**Comment by chadwhitacre** [comment]
I'm trying to get unminified Angular into `vendors.min.js`. I modified our `gulpfile.js` to reference the `angular.js` instead of `angular.min.js`. I double-checked that `angular.js` contains the unminified source. I terminated `gulp default` and ran it again. I removed `vendors.min.js` and reran `gulp default`. I'm still seeing minified Angular in `vendors.min.js`. Ooh ... I guess we are minifying it ourselves even if we're not using their pre-minified version as input ...

**Comment by chadwhitacre** [comment]
Yeah, there we go ...

screen shot 2015-12-07 at 12 33 43 pm

**Comment by chadwhitacre** [comment]
I threw a `debugger` right inside the [`dndDraggable`](https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/angular-drag-and-drop-lists.js#L71) directive, and I'm not hitting it. I _do_ hit one right inside Angular itself.

**Comment by chadwhitacre** [comment]
Can I get an even simpler dnd test to work?

**Comment by chadwhitacre** [comment]
Blurg. Not getting it ... how about `dnd-list`? Is that getting inside of the `dndList` directive?

**Comment by chadwhitacre** [comment]
No.

**Comment by chadwhitacre** [comment]
Is it that I did away with the [`ng-include`](https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/demo/simple/simple-frame.html#L18) in the demo by inlining the contents of `simple.html`? Does `ngInclude` do something more than copy/paste?

**Comment by chadwhitacre** [comment]
https://code.angularjs.org/1.3.14/docs/api/ng/directive/ngInclude

**Comment by chadwhitacre** [comment]
> This directive creates new scope.

Possibly relevant?

**Comment by chadwhitacre** [comment]
https://code.angularjs.org/1.3.14/docs/api/ng/directive/ngScope

:disappointed:

**Comment by chadwhitacre** [comment]
https://code.angularjs.org/1.3.14/docs/guide/scope

**Comment by chadwhitacre** [comment]
> Notice that Angular automatically places `ng-scope` class on elements where scopes are attached.

**Comment by chadwhitacre** [comment]
Demo (working): screen shot 2015-12-07 at 1 13 01 pm

Us (broken): screen shot 2015-12-07 at 1 13 35 pm

**Comment by chadwhitacre** [comment]
I'm trying to use `ng-include`. What is the URL I'm supposed to use?

**Comment by chadwhitacre** [comment]
I've got `<div ng-include="hack.html"></div>` and I'm not seeing a network request for `hack.html`. I do see two network requests for `simple.html` in the demo.

**Comment by chadwhitacre** [comment]
I do see `<!-- ngInclude: hack.html -->` in the output.

**Comment by chadwhitacre** [comment]
> If the source is a string constant, make sure you wrap it in **single quotes**, e.g. `src="'myPartialTemplate.html'"`.

**Comment by chadwhitacre** [comment]
Alright! Still no `debugger` in `dndList` ...

screen shot 2015-12-07 at 1 34 55 pm

**Comment by chadwhitacre** [comment]
`list` is bound to the list we want:

screen shot 2015-12-07 at 1 39 51 pm

**Comment by chadwhitacre** [comment]
What version(s) of Angular does `angular-drag-and-drop-list` support?

**Comment by chadwhitacre** [comment]
I'm not seeing any documentation, but the demo [uses](https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/demo/index.html#L11) 1.4.3.

**Comment by chadwhitacre** [comment]
We're using 1.3.14. If it were 2.0+ that'd be one thing, but isn't it fair to expect `angular-drag-and-drop-lists` to work under 1.3.14 if it's known to work under 1.4.3?

**Comment by chadwhitacre** [comment]
I skimmed Angular's [changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md) and nothing jumped out at me.

**Comment by chadwhitacre** [comment]
Gosh. What's going on?

**Comment by chadwhitacre** [comment]
The `angular-drag-and-drop-lists.js` code is being run.

**Comment by chadwhitacre** [comment]
The `dndLists` module _does_ appear to be loading its directives:

screen shot 2015-12-07 at 2 02 16 pm

http://stackoverflow.com/questions/19087752/list-registered-custom-directives-in-angularjs

**Comment by chadwhitacre** [comment]
@MatthewVita @dmtroyer Can you take a look here when you get a chance? I'm skunked. :-(

I'm going to slink back to the server side to see about pathways in our data model over there ...

**Comment by chadwhitacre** [comment]
I've pushed up my latest state. The problem is that the [callback](https://github.com/saxifrage/cityasacampus/blob/53792dc89defb46d0f887b24ac66748ea104e667/public/angular-drag-and-drop-lists.js#L229) for the `dndList` directive, wherein the real work of the directive takes place, is not being called, despite the presence of a `dnd-list` [attribute](https://github.com/saxifrage/cityasacampus/blob/53792dc89defb46d0f887b24ac66748ea104e667/public/hack.html#L1) on a `UL`.

**Comment by chadwhitacre** [comment]
I reviewed the results for "[angular directive not firing](https://www.google.com/search?q=angular+directive+not+firing)." I don't see Angular's case normalization fouling us up here, and besides, the demo is clearly working. What is the meaningful difference between us and it?

**Comment by chadwhitacre** [comment]
Alright, gonna switch to smashing my head against Rails. :mountain_cableway:

**Comment by dmtroyer** [comment]
Hey yo @whit537, I think I got it working for you. You were so close. You just needed to add the [`dndLists` module as a dependency somewhere](https://github.com/marceljuenemann/angular-drag-and-drop-lists#download--installation), either for the controller or the whole app in `client/index.js`

**Comment by chadwhitacre** [comment]
Thank you, sir. :-)

!m @dmtroyer

**Comment by chadwhitacre** [comment]
I even read that sentence, but glommed it in with bower—"well, I don't think we're using bower ..."

Okay!

screen shot 2015-12-07 at 2 50 54 pm

**Comment by chadwhitacre** [comment]
Now I'm trying to add an "Add" button to make a new pathway list. I am starting with the basic [`ngClick` example](https://code.angularjs.org/1.3.14/docs/api/ng/directive/ngClick). When I click on the "Increment" button in 6a200a6276cc6a151028c32345b63dd8c763f5d7, nothing happens in the UI or the console. I've confirmed that varying `ng-init` has the expected effect on the page. The `ngClick` directive is defined in the [`ng`](https://code.angularjs.org/1.3.14/docs/api/ng) module, which is "loaded by default when an AngularJS application is started." Are we doing something to suppress that? Am I in the wrong scope or something?

**Comment by chadwhitacre** [comment]
screen shot 2015-12-07 at 3 34 15 pm

**Comment by chadwhitacre** [comment]
Okay, false alarm. The button was z-indexed under the header. :-)

screen shot 2015-12-07 at 3 37 18 pm

**Comment by chadwhitacre** [comment]
I propose that we use a UI similar to what we've got on the view side of the map for navigation. Left-aligned instead of right, and with a library of all non-assigned opportunity instances at the far left.

screen shot 2015-12-07 at 3 42 42 pm

**Comment by chadwhitacre** [comment]
It seems like this pathways builder could/should deal directly with the same `topics.json` data structure that http://caac-map.net/v1 expects. We can store the `topics.json` for each map directly in Rails instead of computing it on the server-side.

**Comment by chadwhitacre** [comment]
@timothyfcook For the MVP can we assume exactly one map per `organizer`?

**Comment by timothyfcook** [comment]
If that’s easier for now, then yes.

—

**Comment by chadwhitacre** [comment]
@timothyfcook Okay ...

**Comment by dmtroyer** [comment]
> It seems like this pathways builder could/should deal directly with the same topics.json data structure that http://caac-map.net/v1 expects. We can store the topics.json for each map directly in Rails instead of computing it on the server-side.

This seems like the most expedient method for sure, but would introduce a fair amount of tech debt if we ever wanted to use that pathway data for anything other than the map.

I already started some of the rails side work for this on the branch [`pathways_ftw_2`](https://github.com/saxifrage/cityasacampus/tree/pathways_ftw_2)

**Comment by chadwhitacre** [comment]
@dmtroyer Ah, nice! I was wondering what those branches were for. :-)

**Comment by chadwhitacre** [comment]
screen shot 2015-12-07 at 4 12 15 pm

**Comment by chadwhitacre** [comment]
Now I'm thinking the library should go on the right, so that it's next to the currently selected pathway.

screen shot 2015-12-07 at 4 24 19 pm

**Comment by chadwhitacre** [comment]
> This seems like the most expedient method for sure, but would introduce a fair amount of tech debt if we ever wanted to use that pathway data for anything other than the map.

It would also have implications for modifying opportunity instances. Probably best to store the pathways data in the database granularly, and compute topics.json on the server side.

**Comment by chadwhitacre** [comment]
Had a conversation with @timothyfcook here in the office. We came up with the following requirements for this PR:
- two map workflow states: draft and published
- zero or one maps per organizer per workflow state
  - managed by organizer admins
  - each can include opportunity instances from that organizer
- zero or one map per tenant per workflow state
  - managed by a tenant-wide site admin
  - each can include opportunity instances from all organizers under the tenant
  - this would be what the homepage "Explore the Map" links to
- users should be prevented from _deleting_ opportunity instances that are included on a published map
- users should be able to _modify_ opportunity instances even after a map is published

**Comment by chadwhitacre** [comment]
I've started a to-do in the PR description based on the above comment. Big PR! :-)

**Comment by MatthewVita** [comment]
lookin' good! My only comment is to please put $http calls in a service rather than a controller

/nit-pick

**Comment by chadwhitacre** [comment]
> please put $http calls in a service rather than a controller

Done in 710bcf04b2cc75628c2cbb60aed1932e06cfad8f. :-)

**Comment by chadwhitacre** [comment]
gtsaxubynb

**Comment by dougnorthcook** [comment]
Handles! 
https://drive.google.com/open?id=0B5WKJlscSPykM0VrSHJhckYyRjg

**Comment by chadwhitacre** [comment]
Thank you, sir!

**Comment by chadwhitacre** [comment]
@dougnorthcook I need perms on that link I guess?

**Comment by chadwhitacre** [comment]
bs4prfjlmv

**Comment by chadwhitacre** [comment]
Thanks @dougnorthcook. Ftr here: could use edit and delete icons as well.

**Comment by chadwhitacre** [comment]
Editing roughed in and handles for dnd. Can we get the handles to double up for double lines?

atbobefltn

**Comment by chadwhitacre** [comment]
Tinkering with dnd handles:

jv9jvbispv

**Comment by chadwhitacre** [comment]
@timothyfcook Enabling the whole column as a drop target proved elusive. I think 6f22648d365eff9593a2d732ca1d594afce574dd takes care of the worst of it. Eh?

nexz8swdqe

**Comment by chadwhitacre** [comment]
@timothyfcook approved IRL.

**Comment by chadwhitacre** [comment]
Working on the Rails side in #377.

**Comment by chadwhitacre** [comment]
Rebased on #380. Previous head was 6f22648d365eff9593a2d732ca1d594afce574dd.

**Comment by chadwhitacre** [comment]
Rebased on current #380. Previous head was 52654d30da71eacb5b3ea06e2044ae6970f7c0d2.

**Comment by whit537** [comment]
Erm, rerebased on current #380. Previous head was b69ff9fd84a58877fd7984142ed59b982ffd0ac8.

**Comment by chadwhitacre** [comment]
Looking through the to-do on the description here, I propose that we cut the scope of this PR down by dropping the actual map creation from it. Let's consider this done and ready to merge to `master` when we have the pathway construction UI done. Then let's pick up with actual map creation in a new PR. Objections?

**Comment by chadwhitacre** [comment]
I've updated the description on this PR to reflect current scope and child PRs.

**Comment by dmtroyer** [comment]
> Looking through the to-do on the description here, I propose that we cut the scope of this PR down by dropping the actual map creation from it. Let's consider this done and ready to merge to master when we have the pathway construction UI done. Then let's pick up with actual map creation in a new PR. Objections?

I think this makes sense. I think there will be some logic to clean up once we have maps, since pathways are children of maps and currently we have to create a map on the fly when a mapless pathway is created.

**Comment by chadwhitacre** [comment]
> I think this makes sense.

Cool.

> I think there will be some logic to clean up once we have maps, since pathways are children of maps and currently we have to create a map on the fly when a mapless pathway is created.

Okay, let's revisit once this is landed. I don't think we want/need to create arbitrary maps. Per current requirements (https://github.com/saxifrage/cityasacampus/pull/364#issuecomment-162681923), we only ever need two per organizer (draft and published).

**Comment by chadwhitacre** [comment]
Rebased on master to pick up #380. Previous head was b69ff9fd84a58877fd7984142ed59b982ffd0ac8.

**Pull request closed without merging**
