### PR TITLE
implement pathways

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes https://github.com/saxifrage/caac-map/issues/19.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Had to do some data wrangling in https://github.com/saxifrage/caac-map/pull/53 this morning before I could get back to this.

**Comment by chadwhitacre** [comment]
screen shot 2015-08-28 at 3 50 01 pm

**Comment by chadwhitacre** [comment]
screen shot 2015-08-28 at 5 08 22 pm

**Comment by chadwhitacre** [comment]
screen shot 2015-08-28 at 9 15 28 pm

**Comment by timothyfcook** [comment]
@whit537 do we need to do something before we merge this?

**Comment by chadwhitacre** [comment]
Let's get multi-maps with the latest data on this branch and then we can merge!

**Comment by chadwhitacre** [comment]
Merged per @timothyfcook. "So ready."

**Pull request merged**
