### PR TITLE
bring back nav

### LINKED ISSUE #280: What Pathway Am I On?
For https://github.com/saxifrage/cityasacampus/issues/279 I want to report what pathway the bug is on, but I'm not finding this information anywhere in the UI.

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes #280.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
- [x] generate nav dynamically from topics.json
- [x] add behaviors
- [x] ~~bring back `hr`~~
- [x] ~~move tooltips below nav in z-index~~ don't care right now
- [x] ~~think about smaller screen sizes~~ thought about it, briefly ;-)
- [x] hack new topic names

**Comment by chadwhitacre** [comment]
Dynamic nav:

screen shot 2015-11-02 at 2 21 55 pm

**Comment by cameronscott137** [comment]
@whit537 That's hot.

**Comment by chadwhitacre** [comment]
Gettin' there. ;-)

Currently brainstorming how to make this nav usable. Might need an accordion? Hoping to grab @timothyfcook here in a second ...

**Comment by chadwhitacre** [comment]
@timothyfcook points to https://github.com/saxifrage/caac-map/issues/65.

**Comment by chadwhitacre** [comment]
Bringing over @chelseaerdner's latest design target from https://github.com/saxifrage/caac-map/issues/65#issuecomment-151522584:

screen shot 2015-10-27 at 10 05 40 am

**Comment by chadwhitacre** [comment]
@chelseaerdner Does accordion for subnav fit with your intentions in that mockup?

**Comment by chadwhitacre** [comment]
Ping @timothyfcook. What topics do you wanted hacked for tomorrow?

**Comment by chadwhitacre** [comment]
@timothyfcook is wary of boxing out the map too much, per https://github.com/saxifrage/caac-map/issues/65#issuecomment-151603096:

> This could work. Although we're really boxing in the map and losing space fast....
> 
> Maybe we could keep the menu on the top of bottom running horizontally, but as soon as you make a choice from the menu the menus shrink and fold up so they don't cover the map.

**Comment by chadwhitacre** [comment]
Gonna play around with it here ...

**Comment by timothyfcook** [comment]
Let's go with:
- Healthcare
- Web Development
- Agriculture (map to existing Food + Gardening)
- Art and Design (map to storytelling)
- Robotics (same)
- Manufacturing (map to Designing and Making)
- Filmmaking (Map to Media Making)

(except in alphabetical order)

**Comment by chadwhitacre** [comment]
Copy that, Gold Leader.

**Comment by chelseaerdner** [comment]
Sorry, just saw this. Yes accordion animation applies to the gray nav here @whit537.

**Comment by chadwhitacre** [comment]
Cool, thanks @chelseaerdner. :)

**Comment by chadwhitacre** [comment]
https://github.com/saxifrage/cityasacampus/pull/328#issuecomment-153137504
- [x] Storytelling→Healthcare
- [x] Coding and Gaming→Web Development
- [x] Food + Gardening→Agriculture
- [x] Art + Design→Art and Design
- [x] Robotics→Robotics
- [x] Building + Making→Manufacturing
- [x] Mediamaking→Filmmaking

**Comment by chadwhitacre** [comment]
Topic names hacked in 5fa3b48e0ca53f04f333cea40ad9836edb039d40. Bringing this in for a landing!

**Comment by MatthewVita** [comment]
@whit537, @timothyfcook should we have the same base topics in the explore website's seed data?

**Comment by timothyfcook** [comment]
I just asked Whit to toss those on the Map for a Demo. Not too important, but I'll make a ticket to decide on a final topics lists for the MVP launch.

**Pull request merged**
