### PR TITLE
adds route auth check for dashboard

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Comment by MatthewVita** [comment]
@dmtroyer can you review this real quick?

**Comment by dmtroyer** [comment]
Would it make more sense to redirect the user to `users/login` when they aren't authenticated on the dashboard?

**Comment by MatthewVita** [comment]
@dmtroyer good call. `git commit --amend` to the rescue!

Feel free to merge whenever.

**Comment by MatthewVita** [comment]
thx!

**Pull request merged**
